name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t daniel54088/stan-code-test .

      - name: Verify build output
        run: ls -la /app/build

      - name: Publish image to Docker hub
        run: docker push daniel54088/stan-code-test:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker hub
        run: docker pull daniel54088/stan-code-test:latest
      - name: delete old container
        run: docker rm -f stan-code-test
      - name: Run docker container
        run: docker run -d -p 3000:80 --name stan-code-test daniel54088/stan-code-test:latest
